#ifndef __INCLUDED_SEC_TYPES_H
#define __INCLUDED_SEC_TYPES_H

// All contents in this file is completely made up. Hope it works!
typedef enum
{
    SEC_SUCCESS             = 0x000,
    SEC_OUT_OF_MEMORY,
    SEC_PCI_DEVICE_ACCESS_ERROR,
    SEC_DEVICE_BUSY,
    SEC_INVALID_HOST_REQUEST,
    SEC_EXT_FW_DUPLICATE_KEY_ID,
    SEC_FW_INVALID_LOAD_TYPE,
    SEC_FW_MODULE_NOT_FOUND,
    SEC_FW_SYMBOL_TABLE_MISMATCH,
    SEC_FW_NO_MANIFEST_ENTRY,
    SEC_FW_FS_ELF_LOAD_FAILED,
    SEC_FW_FS_SEEK_OUT_OF_BOUNDS,
    SEC_FW_FS_INVALID_SEEK_TYPE,
    SEC_FW_FS_REOPEN_FILE_ERROR,
    SEC_FW_FS_PAGE_NOT_FOUND,
    SEC_FW_FS_HEADER_LENGTH_MISMATCH,
    SEC_FW_INVALID_PAGE_ADDRESS,
    SEC_FW_FS_FILE_NOT_OPENED,
    SEC_FW_SYSTEM_MEMORY_FULL,
    SEC_FW_INVALID_SYSTEM_ADDRESS,
    SEC_FW_INVALID_MODE,
    SEC_FW_INVALID_NONCE,
    SEC_FW_INVALID_STEP,
    SEC_FW_INVALID_KEY_ATTRIBUTES,
    SEC_FW_TTB_KEY_INVALID,
    SEC_FW_INVALID_KEY_TYPE,
    SEC_FW_INVALID_KEY_SELECT,
    SEC_FW_NO_KEY_SLOTS_AVAILABLE,
    SEC_FW_DRBG_NOT_INITIALIZED,
    SEC_FW_INVALID_HW_COMMAND,
    SEC_FW_EAU_PARITY_ERROR,
    SEC_FW_MOD_EXP_WITHOUT_EXPONENT,
    SEC_FW_INVALID_AES_CTR_MODE,
    SEC_FW_INVALID_CHAIN_MODE,
    SEC_TDP_INIT_FAILED,
    SEC_INVALID_KEY_LENGTH,
    SEC_NULL_POINTER,
    SEC_PCI_DEVICE_NOT_FOUND,
    SEC_INVALID_INPUT,
    SEC_MMAP_INVALID_TGID,
    SEC_MMAP_PHYSMEM_STILL_MAPPED,
    SEC_FW_MODULE_ALREADY_LOADED,
    SEC_FW_HKEY_OPERATION_ERROR,
    SEC_EAU_LOCK_INTERRUPTED,
    SEC_EAU_LOCK_FAILED,
    SEC_RESULT_TEXT,
    SEC_CBC,
    SEC_INVALID_HASH,
    SEC_EXT_FW_INVALID_KEY_ID,
    SEC_NOT_SUPPORTED,
    SEC_INTERNAL_ERROR,
    SEC_PM_INVALID_STATE,
    SEC_FAIL               = 0x00FF,
} sec_result_t;

typedef struct {
    uint16_t host_vendor;
    uint16_t host_device;
    uint16_t host_revision;
    uint16_t sec_vendor;
    uint16_t sec_device;
    uint16_t sec_revision;
} sec_chip_info_t;
typedef uint32_t sec_module_list_t;


#define PCI_VENDOR_INTEL    0x8086 // taken from sec_hal.c
#define PCI_DEVICE_SEC      0x2E64 // taken from sec_hal.c

#endif
